auditbeat.modules:

- module: auditd
  audit_rules: |
    -w /etc/passwd -p wa -k identity
    -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access

- module: file_integrity
  paths:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    - /etc

processors:
# - add_host_metadata: ~
- add_cloud_metadata: ~
# - add_docker_metadata: ~

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "https"
  username: elastic
  # Read PW from auditbeat.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/auditbeat/certs/ca/ca.crt"]

setup.kibana:
  host: "https://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/auditbeat/certs/ca/ca.crt"]

# monitoring.enabled: true
xpack.monitoring.enabled: true

