filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ${path.config}/modules.d/*.yml
    - /mnt/log/*.log
    - /mnt/log/*/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

processors:
# - add_host_metadata: ~
- add_cloud_metadata: ~
# - add_docker_metadata: ~

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "https"
  username: elastic
  # Read PW from filebeat.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

setup.kibana:
  host: "https://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

# monitoring.enabled: true
xpack.monitoring.enabled: true

